Repository META-INT6/REPLANET_RestAPI_V2, pull requests merged in 2023-11, with the labels that each got.

#5 [FEATURE] 테이블 변경 - 사용자 추가
  sql/V2script.sql
  src/main/java/metaint/replanet/rest/campaign/controller/CampaignController.java
  src/main/java/metaint/replanet/rest/campaign/entity/CampaignDescription.java
  src/main/java/metaint/replanet/rest/campaign/repository/ParticipationRepository.java
  src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java
  src/main/java/metaint/replanet/rest/reviews/controller/ReviewController.java
  src/main/java/metaint/replanet/rest/reviews/dto/CampaignDTO.java
  src/main/java/metaint/replanet/rest/reviews/dto/CombineReviewDTO.java
  src/main/java/metaint/replanet/rest/reviews/entity/Campaign.java
  src/main/java/metaint/replanet/rest/reviews/entity/Review.java
  src/main/java/metaint/replanet/rest/reviews/entity/ReviewFile.java
  src/main/java/metaint/replanet/rest/reviews/repository/CampaignReviewRepository.java
  src/main/java/metaint/replanet/rest/reviews/repository/ReviewMemberRepository.java
  src/main/java/metaint/replanet/rest/reviews/repository/ReviewRepository.java
  src/main/java/metaint/replanet/rest/reviews/service/ReviewService.java
  src/main/resources/application.yml
  src/test/java/metaint/replanet/rest/campaign/controller/CampaignControllerTest.java
  src/test/java/metaint/replanet/rest/campaign/service/CampaignServiceTest.java
  src/test/java/metaint/replanet/rest/reviews/repository/ReviewRepositoryTest.java
Labels: review

#11 [Feature] 통계조회 0.2.1
  src/main/java/metaint/replanet/rest/chart/dto/CountAndSumByCategoryDTO.java
  src/main/java/metaint/replanet/rest/chart/dto/DonationByTimeDTO.java
  src/main/java/metaint/replanet/rest/chart/repository/ChartRepository.java
  src/main/java/metaint/replanet/rest/chart/repository/DonationChartRepository.java
  src/main/java/metaint/replanet/rest/chart/service/ChartService.java
  src/test/java/metaint/replanet/rest/chart/repository/ChartRepositoryTest.java
  src/test/java/metaint/replanet/rest/chart/repository/DonationChartRepositoryTest.java
  src/test/java/metaint/replanet/rest/chart/service/ChartServiceTest.java
Labels: chart

#10 [Feature] ORG 정보 수정 0.2.1
  sql/V2script.sql
  src/main/java/metaint/replanet/rest/campaign/repository/ParticipationRepository.java
  src/main/java/metaint/replanet/rest/org/controller/OrgController.java
  src/main/java/metaint/replanet/rest/org/repository/OrgMemberRepository.java
  src/main/java/metaint/replanet/rest/org/repository/OrgRepository.java
  src/main/java/metaint/replanet/rest/org/service/OrgService.java
  src/main/java/metaint/replanet/rest/point/controller/ExchangeController.java
  src/main/resources/application.yml
  src/test/java/metaint/replanet/rest/privacy/repository/privacyRepositoryService.java
  src/test/java/metaint/replanet/rest/privacy/service/privacyServiceTest.java
Labels: organization

#9 [FEATURE] 기부처 리스트 조회 0.1.1
  sql/V2script.sql
  src/main/java/metaint/replanet/rest/campaign/controller/CampaignController.java
  src/main/java/metaint/replanet/rest/campaign/dto/CampaignDesOrgDTO.java
  src/main/java/metaint/replanet/rest/campaign/dto/DonationDTO.java
  src/main/java/metaint/replanet/rest/campaign/dto/ParticipationDTO.java
  src/main/java/metaint/replanet/rest/campaign/dto/RequestCampaignDTO.java
  src/main/java/metaint/replanet/rest/campaign/entity/Campaign.java
  src/main/java/metaint/replanet/rest/campaign/entity/CampaignDescFile.java
  src/main/java/metaint/replanet/rest/campaign/entity/CampaignDescription.java
  src/main/java/metaint/replanet/rest/campaign/entity/Donation.java
  src/main/java/metaint/replanet/rest/campaign/entity/Pay.java
  src/main/java/metaint/replanet/rest/campaign/repository/CampaignAndFileRepository.java
  src/main/java/metaint/replanet/rest/campaign/repository/CampaignDescRepository.java
  src/main/java/metaint/replanet/rest/campaign/repository/CampaignFileRepository.java
  src/main/java/metaint/replanet/rest/campaign/repository/CampaignRepository.java
  src/main/java/metaint/replanet/rest/campaign/repository/ParticipationRepository.java
  src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java
  src/main/java/metaint/replanet/rest/org/controller/OrgController.java
  src/main/java/metaint/replanet/rest/org/service/OrgService.java
  src/test/java/metaint/replanet/rest/campaign/controller/CampaignControllerTest.java
  src/test/java/metaint/replanet/rest/campaign/service/CampaignServiceTest.java
Labels: organization

#8 [FEATURE] 리뷰 사용자 추가 리팩토링
  sql/V1script.sql
  src/main/java/metaint/replanet/rest/org/service/OrgService.java
  src/main/java/metaint/replanet/rest/reviews/controller/ReviewController.java
  src/main/java/metaint/replanet/rest/reviews/repository/CampaignReviewRepository.java
  src/main/java/metaint/replanet/rest/reviews/repository/ReviewRepository.java
  src/main/java/metaint/replanet/rest/reviews/service/ReviewService.java
  src/test/java/metaint/replanet/rest/org/service/OrganizationServiceTest.java
  src/test/java/metaint/replanet/rest/reviews/repository/CampaignReviewRepositoryTest.java
  src/test/java/metaint/replanet/rest/reviews/repository/ReviewRepositoryTest.java
  src/test/java/metaint/replanet/rest/reviews/service/ReviewServiceTest.java
Labels: review

#17 [Feature] ORG 정보 수정 0.2.2, 기부처 관리 0.1.1
  src/main/java/metaint/replanet/rest/org/controller/OrgController.java
  src/main/java/metaint/replanet/rest/org/dto/OrgRequestDTO.java
  src/main/java/metaint/replanet/rest/org/entity/Organization.java
  src/main/java/metaint/replanet/rest/org/repository/OrgMemberRepository.java
  src/main/java/metaint/replanet/rest/org/service/OrgService.java
  src/test/java/metaint/replanet/rest/privacy/repository/privacyRepositoryService.java
  src/test/java/metaint/replanet/rest/privacy/service/privacyServiceTest.java
Labels: organization

#16 [FEATURE] 기부처 상세페이지 조회 0.1.2
  src/main/java/metaint/replanet/rest/campaign/controller/CampaignController.java
  src/main/java/metaint/replanet/rest/campaign/repository/CampaignRepository.java
  src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java
Labels: organization
