Repository META-INT6/REPLANET_RestAPI_V2, pull requests merged in 2023-12, with the labels that each got.

#19 [Feature] 통계 조회 0.2.3
  src/main/java/metaint/replanet/rest/chart/dto/CountAndSumByMonthlyDTO.java
  src/main/java/metaint/replanet/rest/chart/repository/ChartRepository.java
  src/main/java/metaint/replanet/rest/chart/repository/DonationChartRepository.java
  src/main/java/metaint/replanet/rest/chart/service/ChartService.java
  src/test/java/metaint/replanet/rest/chart/repository/ChartRepositoryTest.java
  src/test/java/metaint/replanet/rest/chart/repository/DonationChartRepositoryTest.java
  src/test/java/metaint/replanet/rest/chart/service/ChartServiceTest.java
Labels: chart

#24 [BUGFIX] TinyMCE 텍스트 에디터 윈도우 이미지 경로 설정
  src/main/java/metaint/replanet/rest/reviews/dto/OrganizationDTO.java
  src/main/java/metaint/replanet/rest/reviews/service/ReviewService.java
Labels: review

#23 [Feature] 카카오로그인 0.1.1
  src/main/java/metaint/replanet/rest/auth/config/OAuth2Config.java
  src/main/java/metaint/replanet/rest/auth/controller/KakaoController.java
  src/main/java/metaint/replanet/rest/auth/dto/KakaoTokenRequest.java
  src/main/java/metaint/replanet/rest/auth/oauth2/PrincipalDetails.java
  src/main/java/metaint/replanet/rest/auth/oauth2/PrincipalOauth2UserService.java
  src/main/java/metaint/replanet/rest/auth/repository/MemberRepository.java
  src/main/resources/application.yml
Labels: socialLogin

#29 [Feature] ORG 정보 수정 0.2.5
  src/main/java/metaint/replanet/rest/org/controller/OrgController.java
  src/main/java/metaint/replanet/rest/org/repository/OrgMemberRepository.java
  src/main/java/metaint/replanet/rest/org/service/OrgService.java
  src/main/java/metaint/replanet/rest/privacy/service/PrivacyService.java
Labels: organization

#31 [Feature] 카카오 로그인 0.1.4
  src/main/java/metaint/replanet/rest/auth/controller/KakaoController.java
  src/main/java/metaint/replanet/rest/privacy/service/PrivacyService.java
Labels: socialLogin

#34 [Feature] ORG 정보 수정 0.2.7
  src/main/java/metaint/replanet/rest/auth/dto/MemberRequestDto.java
  src/main/java/metaint/replanet/rest/auth/dto/TokenDto.java
  src/main/java/metaint/replanet/rest/auth/entity/Member.java
  src/main/java/metaint/replanet/rest/auth/jwt/TokenProvider.java
  src/main/java/metaint/replanet/rest/auth/service/AuthService.java
Labels: organization

#35 [Fix] 기부처 탈퇴시 org도 함께 처리되게 로직 구현
  src/main/java/metaint/replanet/rest/org/repository/OrgRepository.java
  src/main/java/metaint/replanet/rest/org/service/OrgService.java
Labels: organization

#36 [BUGFIX] 캠페인 엔티티 변경 0.1.6
  sql/V1script.sql
  sql/V2script.sql
  src/main/java/metaint/replanet/rest/bookmark/entity/Bookmark.java
  src/main/java/metaint/replanet/rest/bookmark/repository/BookmarkRepository.java
  src/main/java/metaint/replanet/rest/bookmark/service/BookmarkService.java
  src/main/java/metaint/replanet/rest/campaign/dto/CampaignDescFileDTO.java
  src/main/java/metaint/replanet/rest/campaign/entity/Campaign.java
  src/main/java/metaint/replanet/rest/campaign/entity/CampaignDescFile.java
  src/main/java/metaint/replanet/rest/campaign/repository/CampaignRepository.java
  src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java
Labels: campaign, organization

#39 [Fix] 통계 조회 0.2.4
  src/main/java/metaint/replanet/rest/chart/repository/ChartRepository.java
  src/main/java/metaint/replanet/rest/chart/repository/DonationChartRepository.java
Labels: chart

#38 [BUGFIX] 캠페인 엔티티, 북마크 엔티티 설정 변경 0.1.7
  src/main/java/metaint/replanet/rest/bookmark/entity/Bookmark.java
  src/main/java/metaint/replanet/rest/campaign/entity/Campaign.java
  src/main/java/metaint/replanet/rest/campaign/entity/CampaignDescFile.java
  src/main/java/metaint/replanet/rest/campaign/entity/Organization.java
  src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java
Labels: campaign, bookmark

#37 [Fix] 리뷰 등록/수정 버그 수정 중
  src/main/java/metaint/replanet/rest/reviews/controller/ReviewController.java
  src/main/java/metaint/replanet/rest/reviews/service/ReviewService.java
Labels: review

#40 [Fix] 탈퇴회원, 탈퇴기부처회원 로그인 방지
  sql/V2script.sql
  src/main/java/metaint/replanet/rest/auth/controller/AuthController.java
  src/main/java/metaint/replanet/rest/auth/dto/MemberRequestDto.java
  src/main/java/metaint/replanet/rest/auth/dto/TokenDto.java
  src/main/java/metaint/replanet/rest/auth/repository/MemberRepository.java
  src/main/java/metaint/replanet/rest/auth/service/AuthService.java
  src/main/java/metaint/replanet/rest/campaign/dto/MemberDTO.java
  src/main/java/metaint/replanet/rest/campaign/entity/Member.java
  src/main/java/metaint/replanet/rest/chart/entity/Member.java
  src/main/java/metaint/replanet/rest/pay/dto/MemberDTO.java
  src/main/java/metaint/replanet/rest/pay/entity/Member.java
  src/main/java/metaint/replanet/rest/point/dto/MemberDTO.java
  src/main/java/metaint/replanet/rest/point/entity/Member.java
  src/main/java/metaint/replanet/rest/privacy/dto/MemberDTO.java
  src/main/java/metaint/replanet/rest/privacy/entity/Member.java
  src/main/java/metaint/replanet/rest/privacy/service/PrivacyService.java
  src/main/java/metaint/replanet/rest/reviews/dto/MemberDTO.java
Labels: auth

#42 [REFACTOR] 해당 재단 리뷰 전체 조회 쿼리 수정
  src/main/java/metaint/replanet/rest/reviews/repository/CampaignReviewRepository.java
Labels: review

#43 [Fix] Auth 디버깅용 log 추가
  src/main/java/metaint/replanet/rest/auth/controller/AuthController.java
Labels: auth

#44 [Feature] 통계 조회 0.2.11
  src/main/java/metaint/replanet/rest/chart/controller/ChartController.java
  src/main/java/metaint/replanet/rest/chart/dto/DonationByTimeDTO.java
  src/main/java/metaint/replanet/rest/chart/repository/DonationChartRepository.java
  src/main/java/metaint/replanet/rest/chart/service/ChartService.java
  src/test/java/metaint/replanet/rest/chart/service/ChartServiceTest.java
Labels: chart
